### PR TITLE
LA225 - browse workspace to download-to-mem

### PR DESCRIPTION
**Pull request by JohnAD**
When getting a search result or seeing the Ondsel workpage, a Workspace now brings up dialog asking what you want to do:

image

If you choose "open" you get another dialog allowing you to select one file to download:

image

### CODE REVIEW

**Review by amrit3701 — COMMENTED** [review]
I keep getting the Ondsel ES dialog every time I click on a share link. However, for workspaces, the dialog only appears the first time; after that, it always opens the workspace in the browser. I have also cleared all cache, logged out, and logged back in, but the issue persists.

@JohnAD

**Review by amrit3701 — APPROVED** [review]
Tested, able to open file from workspace.

**Review by amrit3701 — COMMENTED** [review]
@JohnAD 

I reviewed the PR again, and now the second dialog appears immediately after selecting the 'Open file in Ondsel ES' option. However, in the second dialog, the user has to guess where to click to access the workspace files. I was also confused at first, but then I clicked on 'Workspace' in the Workspace column and saw the files. I'm not sure how much effort it would take, but could we automatically call the fetch files API after the second dialog opens? It might make the dialog hang momentarily, but it would save the user from having to figure it out.

Another option would be to show a progress bar or spinning icon after calling the fetch files API, though I assume that would require multithreading.

**Review by amrit3701 — APPROVED** [review]
Awesome.

**Review by pieterhijma — CHANGES_REQUESTED** [review]
Just a small change that I prefer, but otherwise looks good!

**Pull request merged**
